name: bluxkart
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.6.2







dependencies:
  flutter:
    sdk: flutter

  velocity_x: ^4.3.0
  get: ^4.6.6
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_messaging: ^15.2.2
  firebase_storage: ^12.4.2
  image_picker: ^1.1.2
  razorpay_flutter: ^1.0.1
  dio: ^5.3.3
  url_launcher: ^6.1.5
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.3.10

flutter_native_splash:
  color: "#000000"
  android: true
  ios: true

  
  
  
  
  






flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/tshirts/
    - assets/images/bags/
    - assets/images/Caps/
    - assets/images/mugs/
    - assets/images/
    - assets/Logo/
    - assets/lottie/AddedtoCart.json
  


  
  
  
  
  
  
  
  
  
  
  
  
  
  

  
  
